'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property jumlahKriteria() As Decimal
            Get
                Return CType(Me("jumlahKriteria"),Decimal)
            End Get
            Set
                Me("jumlahKriteria") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property jumlahAlternatif() As Decimal
            Get
                Return CType(Me("jumlahAlternatif"),Decimal)
            End Get
            Set
                Me("jumlahAlternatif") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kriteria2() As String
            Get
                Return CType(Me("kriteria2"),String)
            End Get
            Set
                Me("kriteria2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kriteria1() As String
            Get
                Return CType(Me("kriteria1"),String)
            End Get
            Set
                Me("kriteria1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kriteria3() As String
            Get
                Return CType(Me("kriteria3"),String)
            End Get
            Set
                Me("kriteria3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kriteria4() As String
            Get
                Return CType(Me("kriteria4"),String)
            End Get
            Set
                Me("kriteria4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kriteria5() As String
            Get
                Return CType(Me("kriteria5"),String)
            End Get
            Set
                Me("kriteria5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property alternatif1() As String
            Get
                Return CType(Me("alternatif1"),String)
            End Get
            Set
                Me("alternatif1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property alternatif2() As String
            Get
                Return CType(Me("alternatif2"),String)
            End Get
            Set
                Me("alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property alternatif3() As String
            Get
                Return CType(Me("alternatif3"),String)
            End Get
            Set
                Me("alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property alternatif4() As String
            Get
                Return CType(Me("alternatif4"),String)
            End Get
            Set
                Me("alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property alternatif5() As String
            Get
                Return CType(Me("alternatif5"),String)
            End Get
            Set
                Me("alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property kriteria1kriteria2() As Integer
            Get
                Return CType(Me("kriteria1kriteria2"),Integer)
            End Get
            Set
                Me("kriteria1kriteria2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1kriteria3() As Integer
            Get
                Return CType(Me("kriteria1kriteria3"),Integer)
            End Get
            Set
                Me("kriteria1kriteria3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1kriteria4() As Integer
            Get
                Return CType(Me("kriteria1kriteria4"),Integer)
            End Get
            Set
                Me("kriteria1kriteria4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1kriteria5() As Integer
            Get
                Return CType(Me("kriteria1kriteria5"),Integer)
            End Get
            Set
                Me("kriteria1kriteria5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2kriteria3() As Integer
            Get
                Return CType(Me("kriteria2kriteria3"),Integer)
            End Get
            Set
                Me("kriteria2kriteria3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2kriteria4() As Integer
            Get
                Return CType(Me("kriteria2kriteria4"),Integer)
            End Get
            Set
                Me("kriteria2kriteria4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2kriteria5() As Integer
            Get
                Return CType(Me("kriteria2kriteria5"),Integer)
            End Get
            Set
                Me("kriteria2kriteria5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3kriteria4() As Integer
            Get
                Return CType(Me("kriteria3kriteria4"),Integer)
            End Get
            Set
                Me("kriteria3kriteria4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3kriteria5() As Integer
            Get
                Return CType(Me("kriteria3kriteria5"),Integer)
            End Get
            Set
                Me("kriteria3kriteria5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4kriteria5() As Integer
            Get
                Return CType(Me("kriteria4kriteria5"),Integer)
            End Get
            Set
                Me("kriteria4kriteria5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif1alternatif2() As Integer
            Get
                Return CType(Me("kriteria1alternatif1alternatif2"),Integer)
            End Get
            Set
                Me("kriteria1alternatif1alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif1alternatif3() As Integer
            Get
                Return CType(Me("kriteria1alternatif1alternatif3"),Integer)
            End Get
            Set
                Me("kriteria1alternatif1alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif1alternatif4() As Integer
            Get
                Return CType(Me("kriteria1alternatif1alternatif4"),Integer)
            End Get
            Set
                Me("kriteria1alternatif1alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif1alternatif5() As Integer
            Get
                Return CType(Me("kriteria1alternatif1alternatif5"),Integer)
            End Get
            Set
                Me("kriteria1alternatif1alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif1alternatif2() As Integer
            Get
                Return CType(Me("kriteria2alternatif1alternatif2"),Integer)
            End Get
            Set
                Me("kriteria2alternatif1alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif1alternatif3() As Integer
            Get
                Return CType(Me("kriteria2alternatif1alternatif3"),Integer)
            End Get
            Set
                Me("kriteria2alternatif1alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif1alternatif4() As Integer
            Get
                Return CType(Me("kriteria2alternatif1alternatif4"),Integer)
            End Get
            Set
                Me("kriteria2alternatif1alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif1alternatif5() As Integer
            Get
                Return CType(Me("kriteria2alternatif1alternatif5"),Integer)
            End Get
            Set
                Me("kriteria2alternatif1alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif1alternatif2() As Integer
            Get
                Return CType(Me("kriteria3alternatif1alternatif2"),Integer)
            End Get
            Set
                Me("kriteria3alternatif1alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif1alternatif3() As Integer
            Get
                Return CType(Me("kriteria3alternatif1alternatif3"),Integer)
            End Get
            Set
                Me("kriteria3alternatif1alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif1alternatif4() As Integer
            Get
                Return CType(Me("kriteria3alternatif1alternatif4"),Integer)
            End Get
            Set
                Me("kriteria3alternatif1alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif1alternatif5() As Integer
            Get
                Return CType(Me("kriteria3alternatif1alternatif5"),Integer)
            End Get
            Set
                Me("kriteria3alternatif1alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif1alternatif2() As Integer
            Get
                Return CType(Me("kriteria4alternatif1alternatif2"),Integer)
            End Get
            Set
                Me("kriteria4alternatif1alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif1alternatif3() As Integer
            Get
                Return CType(Me("kriteria4alternatif1alternatif3"),Integer)
            End Get
            Set
                Me("kriteria4alternatif1alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif1alternatif4() As Integer
            Get
                Return CType(Me("kriteria4alternatif1alternatif4"),Integer)
            End Get
            Set
                Me("kriteria4alternatif1alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif1alternatif5() As Integer
            Get
                Return CType(Me("kriteria4alternatif1alternatif5"),Integer)
            End Get
            Set
                Me("kriteria4alternatif1alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif1alternatif2() As Integer
            Get
                Return CType(Me("kriteria5alternatif1alternatif2"),Integer)
            End Get
            Set
                Me("kriteria5alternatif1alternatif2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif1alternatif3() As Integer
            Get
                Return CType(Me("kriteria5alternatif1alternatif3"),Integer)
            End Get
            Set
                Me("kriteria5alternatif1alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif1alternatif4() As Integer
            Get
                Return CType(Me("kriteria5alternatif1alternatif4"),Integer)
            End Get
            Set
                Me("kriteria5alternatif1alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif1alternatif5() As Integer
            Get
                Return CType(Me("kriteria5alternatif1alternatif5"),Integer)
            End Get
            Set
                Me("kriteria5alternatif1alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif2alternatif3() As Integer
            Get
                Return CType(Me("kriteria1alternatif2alternatif3"),Integer)
            End Get
            Set
                Me("kriteria1alternatif2alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif2alternatif4() As Integer
            Get
                Return CType(Me("kriteria1alternatif2alternatif4"),Integer)
            End Get
            Set
                Me("kriteria1alternatif2alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif2alternatif5() As Integer
            Get
                Return CType(Me("kriteria1alternatif2alternatif5"),Integer)
            End Get
            Set
                Me("kriteria1alternatif2alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif3alternatif4() As Integer
            Get
                Return CType(Me("kriteria1alternatif3alternatif4"),Integer)
            End Get
            Set
                Me("kriteria1alternatif3alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif3alternatif5() As Integer
            Get
                Return CType(Me("kriteria1alternatif3alternatif5"),Integer)
            End Get
            Set
                Me("kriteria1alternatif3alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria1alternatif4alternatif5() As Integer
            Get
                Return CType(Me("kriteria1alternatif4alternatif5"),Integer)
            End Get
            Set
                Me("kriteria1alternatif4alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif2alternatif3() As Integer
            Get
                Return CType(Me("kriteria2alternatif2alternatif3"),Integer)
            End Get
            Set
                Me("kriteria2alternatif2alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif2alternatif5() As Integer
            Get
                Return CType(Me("kriteria2alternatif2alternatif5"),Integer)
            End Get
            Set
                Me("kriteria2alternatif2alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif2alternatif4() As Integer
            Get
                Return CType(Me("kriteria2alternatif2alternatif4"),Integer)
            End Get
            Set
                Me("kriteria2alternatif2alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif3alternatif4() As Integer
            Get
                Return CType(Me("kriteria2alternatif3alternatif4"),Integer)
            End Get
            Set
                Me("kriteria2alternatif3alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif3alternatif5() As Integer
            Get
                Return CType(Me("kriteria2alternatif3alternatif5"),Integer)
            End Get
            Set
                Me("kriteria2alternatif3alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria2alternatif4alternatif5() As Integer
            Get
                Return CType(Me("kriteria2alternatif4alternatif5"),Integer)
            End Get
            Set
                Me("kriteria2alternatif4alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif2alternatif3() As Integer
            Get
                Return CType(Me("kriteria3alternatif2alternatif3"),Integer)
            End Get
            Set
                Me("kriteria3alternatif2alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif2alternatif4() As Integer
            Get
                Return CType(Me("kriteria3alternatif2alternatif4"),Integer)
            End Get
            Set
                Me("kriteria3alternatif2alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif2alternatif5() As Integer
            Get
                Return CType(Me("kriteria3alternatif2alternatif5"),Integer)
            End Get
            Set
                Me("kriteria3alternatif2alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif3alternatif4() As Integer
            Get
                Return CType(Me("kriteria3alternatif3alternatif4"),Integer)
            End Get
            Set
                Me("kriteria3alternatif3alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif3alternatif5() As Integer
            Get
                Return CType(Me("kriteria3alternatif3alternatif5"),Integer)
            End Get
            Set
                Me("kriteria3alternatif3alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria3alternatif4alternatif5() As Integer
            Get
                Return CType(Me("kriteria3alternatif4alternatif5"),Integer)
            End Get
            Set
                Me("kriteria3alternatif4alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif3alternatif4() As Integer
            Get
                Return CType(Me("kriteria4alternatif3alternatif4"),Integer)
            End Get
            Set
                Me("kriteria4alternatif3alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif3alternatif5() As Integer
            Get
                Return CType(Me("kriteria4alternatif3alternatif5"),Integer)
            End Get
            Set
                Me("kriteria4alternatif3alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif2alternatif3() As Integer
            Get
                Return CType(Me("kriteria4alternatif2alternatif3"),Integer)
            End Get
            Set
                Me("kriteria4alternatif2alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif2alternatif4() As Integer
            Get
                Return CType(Me("kriteria4alternatif2alternatif4"),Integer)
            End Get
            Set
                Me("kriteria4alternatif2alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif2alternatif5() As Integer
            Get
                Return CType(Me("kriteria4alternatif2alternatif5"),Integer)
            End Get
            Set
                Me("kriteria4alternatif2alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria4alternatif4alternatif5() As Integer
            Get
                Return CType(Me("kriteria4alternatif4alternatif5"),Integer)
            End Get
            Set
                Me("kriteria4alternatif4alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif2alternatif3() As Integer
            Get
                Return CType(Me("kriteria5alternatif2alternatif3"),Integer)
            End Get
            Set
                Me("kriteria5alternatif2alternatif3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif2alternatif4() As Integer
            Get
                Return CType(Me("kriteria5alternatif2alternatif4"),Integer)
            End Get
            Set
                Me("kriteria5alternatif2alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif2alternatif5() As Integer
            Get
                Return CType(Me("kriteria5alternatif2alternatif5"),Integer)
            End Get
            Set
                Me("kriteria5alternatif2alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif4alternatif5() As Integer
            Get
                Return CType(Me("kriteria5alternatif4alternatif5"),Integer)
            End Get
            Set
                Me("kriteria5alternatif4alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif3alternatif4() As Integer
            Get
                Return CType(Me("kriteria5alternatif3alternatif4"),Integer)
            End Get
            Set
                Me("kriteria5alternatif3alternatif4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property kriteria5alternatif3alternatif5() As Integer
            Get
                Return CType(Me("kriteria5alternatif3alternatif5"),Integer)
            End Get
            Set
                Me("kriteria5alternatif3alternatif5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pemilihan Universitas Dengan Metode AHP")>  _
        Public Property TitleModelAHP() As String
            Get
                Return CType(Me("TitleModelAHP"),String)
            End Get
            Set
                Me("TitleModelAHP") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=D:\files\skripsi\aplikasi\Database\A"& _ 
            "hpUniversitas.mdb")>  _
        Public ReadOnly Property AhpUniversitasConnectionString() As String
            Get
                Return CType(Me("AhpUniversitasConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PemilihanUniversitasAHP.My.MySettings
            Get
                Return Global.PemilihanUniversitasAHP.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
